// 30-client-sdk/31-client-evaluation/vue/src/LdSession.vue
<script setup>
/**
 * Mounts the Vue SDK only after login, with the real user context.
 * Does not initialize anonymously then identify — that is example 32.
 * LaunchDarkly: ldInit, ready, change events
 * https://launchdarkly.com/docs/sdk/client-side/vue
 * https://launchdarkly.com/docs/sdk/features/flag-changes
 *
 * The slot waits for this client's `ready`. The plugin's shared ready ref stays
 * true from an earlier session, and `useLDFlag` reads `variation` once at setup
 * when it believes the client is ready — evaluating a child too early pins it to
 * the code default until the next `change:`.
 */
import { onUnmounted, ref } from "vue";
import { ldInit } from "launchdarkly-vue-client-sdk";
import { formatChangeDetail } from "./ld.js";

const props = defineProps({
  clientSideId: { type: String, required: true },
  username: { type: String, required: true },
  onSdkEvent: { type: Function, required: true },
});

const [, ldClient] = ldInit({
  clientSideID: props.clientSideId,
  context: { kind: "user", key: props.username },
  streaming: true,
});

const ready = ref(false);

function onReady() {
  props.onSdkEvent("initialize", `key=${props.username}`);
  ready.value = true;
}

function onFailed(err) {
  props.onSdkEvent("failed", String(err?.message || err));
  ready.value = true;
}

function onChange(payload) {
  const keys = formatChangeDetail(payload);
  props.onSdkEvent("change", keys ? `flags=${keys}` : "(stream update)");
}

ldClient.on("ready", onReady);
ldClient.on("failed", onFailed);
ldClient.on("change", onChange);

onUnmounted(() => {
  ldClient.off("ready", onReady);
  ldClient.off("failed", onFailed);
  ldClient.off("change", onChange);
  props.onSdkEvent("close", "client discarded (logout / re-init)");
  if (typeof ldClient.close === "function") {
    try {
      ldClient.close();
    } catch (_err) {
      /* ignore */
    }
  }
});
</script>

<template>
  <slot v-if="ready" />
  <p v-else class="hint">Connecting to LaunchDarkly…</p>
</template>

// 30-client-sdk/31-client-evaluation/react/src/ld-session.jsx
/**
 * 31-client-evaluation React Web SDK session.
 * LaunchDarkly: createLDReactProvider, useStringVariation, useBoolVariation, change:
 * https://launchdarkly.com/docs/sdk/client-side/react/react-web
 */
import { useEffect, useMemo, useRef } from "react";
import {
  createLDReactProvider,
  useBoolVariation,
  useInitializationStatus,
  useLDClient,
  useStringVariation,
} from "@launchdarkly/react-sdk";

export const FLAG_HIGHLIGHT = "enable-client-grid-highlight";
export const FLAG_COUNT = "show-client-move-count";

const COLORS = new Set(["green", "yellow", "red", "blue", "purple"]);

export function interpretHighlight(raw) {
  if (typeof raw === "string" && COLORS.has(raw.trim().toLowerCase())) {
    return raw.trim().toLowerCase();
  }
  return "none";
}

function formatChangeDetail(payload) {
  if (payload == null) return "";
  if (Array.isArray(payload)) return payload.join(", ");
  if (typeof payload === "object") return Object.keys(payload).join(", ");
  return String(payload);
}

/**
 * Mounts the React Web SDK only after login, with the real user context.
 * Does not initialize anonymously then identify — that is example 32.
 */
export function LdSession({ clientSideId, username, onSdkEvent, children }) {
  const Provider = useMemo(
    () =>
      createLDReactProvider(clientSideId, { kind: "user", key: username }, {
        ldOptions: { streaming: true },
      }),
    [clientSideId, username]
  );
  return (
    <Provider>
      <LdBridge username={username} onSdkEvent={onSdkEvent}>
        {children}
      </LdBridge>
    </Provider>
  );
}

function LdBridge({ username, onSdkEvent, children }) {
  const { status } = useInitializationStatus();
  const ldClient = useLDClient();
  const initLogged = useRef(false);

  useEffect(() => {
    if (status !== "complete" || initLogged.current) return;
    initLogged.current = true;
    onSdkEvent("initialize", `key=${username}`);
  }, [status, username, onSdkEvent]);

  /**
   * Streaming flag updates — the variation hooks re-render; this listener is
   * only for the lab SDK call log (not WASD).
   * LaunchDarkly: change events
   * https://launchdarkly.com/docs/sdk/features/flag-changes
   */
  useEffect(() => {
    if (!ldClient || typeof ldClient.on !== "function") return undefined;
    const onChange = (payload) => {
      const keys = formatChangeDetail(payload);
      onSdkEvent("change", keys ? `flags=${keys}` : "(stream update)");
    };
    ldClient.on("change", onChange);
    return () => {
      if (typeof ldClient.off === "function") ldClient.off("change", onChange);
    };
  }, [ldClient, onSdkEvent]);

  const clientRef = useRef(null);
  clientRef.current = ldClient;

  useEffect(() => {
    return () => {
      onSdkEvent("close", "client discarded (logout / re-init)");
      const client = clientRef.current;
      if (client && typeof client.close === "function") {
        try {
          client.close();
        } catch (_err) {
          /* ignore */
        }
      }
    };
  }, [username, onSdkEvent]);

  return children;
}

/**
 * Read flags via typed variation hooks (React Web SDK).
 * Keys stay kebab-case — not the deprecated camelCase useFlags path.
 */
export function useGridFlags() {
  const highlightRaw = useStringVariation(FLAG_HIGHLIGHT, "none");
  const showCount = useBoolVariation(FLAG_COUNT, false);
  return {
    highlight: interpretHighlight(highlightRaw),
    showCount: Boolean(showCount),
  };
}
